#!/usr/bin/env bash
# ============================================================
# Deploy Self-Hosted Supabase to Hetzner
# ============================================================
# Run this FROM YOUR MAC to set up the Hetzner instance.
#
# Prerequisites:
#   - SSH access to your Hetzner server
#   - Server has Docker + Docker Compose installed
#
# Usage:
#   ./deploy-hetzner.sh user@your-hetzner-ip
#
# What it does:
#   1. Copies Supabase infra + migrations to the server
#   2. Generates JWT keys on the server
#   3. Starts Docker Compose stack
#   4. Runs all 14 migrations
#   5. Prints connection details for your apps
# ============================================================

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: $0 user@server-ip [domain]"
  echo ""
  echo "  user@server-ip   SSH target (e.g., root@65.21.x.x)"
  echo "  domain           Optional: domain pointing at the server (e.g., db.contentos.app)"
  echo "                   If omitted, uses the server IP."
  exit 1
fi

SERVER="$1"
DOMAIN="${2:-}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="${SCRIPT_DIR}/.."

echo "=== ContentOS Supabase Deployment ==="
echo "Target: ${SERVER}"
echo "Domain: ${DOMAIN:-<using server IP>}"
echo ""

# ── Step 1: Install Docker on server if needed ──
echo "Step 1: Checking Docker on server..."
ssh "${SERVER}" 'command -v docker >/dev/null 2>&1 || {
  echo "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable docker
  systemctl start docker
  echo "Docker installed."
}'

ssh "${SERVER}" 'command -v docker-compose >/dev/null 2>&1 || docker compose version >/dev/null 2>&1 || {
  echo "Installing Docker Compose plugin..."
  apt-get update -qq && apt-get install -y -qq docker-compose-plugin
  echo "Docker Compose installed."
}'

echo "Docker ready."

# ── Step 2: Copy files to server ──
echo ""
echo "Step 2: Copying files to server..."

ssh "${SERVER}" "mkdir -p /opt/contentos/supabase /opt/contentos/migrations /opt/contentos/scripts"

# Copy Supabase infra
scp -r "${SCRIPT_DIR}/supabase/docker-compose.yml" "${SERVER}:/opt/contentos/supabase/"
scp -r "${SCRIPT_DIR}/supabase/.env.example" "${SERVER}:/opt/contentos/supabase/"
scp -r "${SCRIPT_DIR}/supabase/volumes" "${SERVER}:/opt/contentos/supabase/"

# Copy migrations
scp "${PROJECT_ROOT}/supabase/migrations/"*.sql "${SERVER}:/opt/contentos/migrations/"

# Copy scripts
scp "${SCRIPT_DIR}/scripts/generate-keys.sh" "${SERVER}:/opt/contentos/scripts/"
scp "${SCRIPT_DIR}/scripts/run-migrations.sh" "${SERVER}:/opt/contentos/scripts/"

echo "Files copied."

# ── Step 3: Generate keys + create .env on server ──
echo ""
echo "Step 3: Generating keys and configuring..."

POSTGRES_PASSWORD=$(openssl rand -hex 24)

ssh "${SERVER}" bash <<REMOTE_SCRIPT
set -euo pipefail
cd /opt/contentos

# Generate JWT keys
chmod +x scripts/generate-keys.sh
bash scripts/generate-keys.sh supabase/.env.keys

# Source the generated keys
source supabase/.env.keys

# Determine external URL
if [ -n "${DOMAIN}" ]; then
  EXTERNAL_URL="https://${DOMAIN}"
else
  SERVER_IP=\$(hostname -I | awk '{print \$1}')
  EXTERNAL_URL="http://\${SERVER_IP}:8000"
fi

# Create .env
cat > supabase/.env <<EOF
# Generated by deploy-hetzner.sh on \$(date -u +"%Y-%m-%d %H:%M:%S UTC")

JWT_SECRET=\${JWT_SECRET}
JWT_EXP=3600
ANON_KEY=\${ANON_KEY}
SERVICE_ROLE_KEY=\${SERVICE_ROLE_KEY}

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=postgres
POSTGRES_PORT=5432

API_EXTERNAL_URL=\${EXTERNAL_URL}
SITE_URL=\${EXTERNAL_URL}

KONG_HTTP_PORT=8000
KONG_HTTPS_PORT=8443
STUDIO_PORT=3001

DISABLE_SIGNUP=false
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
ADDITIONAL_REDIRECT_URLS=http://localhost:3000,http://localhost:3100

ENABLE_LINKEDIN=false
ENABLE_TWITTER=false
ENABLE_GOOGLE=false

STUDIO_DEFAULT_ORGANIZATION=Content Platform
STUDIO_DEFAULT_PROJECT=Content OS
SECRET_KEY_BASE=\$(openssl rand -hex 32)
EOF

echo ".env created at /opt/contentos/supabase/.env"
REMOTE_SCRIPT

echo "Configuration ready."

# ── Step 4: Start Docker Compose ──
echo ""
echo "Step 4: Starting Supabase stack..."

ssh "${SERVER}" bash <<'REMOTE_SCRIPT'
cd /opt/contentos/supabase
docker compose pull
docker compose up -d

echo "Waiting for services to be healthy..."
sleep 15

# Check health
docker compose ps
REMOTE_SCRIPT

echo "Stack running."

# ── Step 5: Run migrations ──
echo ""
echo "Step 5: Running migrations..."

ssh "${SERVER}" bash <<'REMOTE_SCRIPT'
set -euo pipefail
cd /opt/contentos

source supabase/.env
DB_URL="postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}"

# Wait for postgres
RETRIES=30
until docker compose -f supabase/docker-compose.yml exec -T postgres pg_isready -U postgres 2>/dev/null; do
  RETRIES=$((RETRIES - 1))
  if [ $RETRIES -le 0 ]; then
    echo "Error: PostgreSQL not ready"
    exit 1
  fi
  sleep 2
done

# Ensure extensions
docker compose -f supabase/docker-compose.yml exec -T postgres psql -U postgres -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"
docker compose -f supabase/docker-compose.yml exec -T postgres psql -U postgres -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"

# Create migration tracking table
docker compose -f supabase/docker-compose.yml exec -T postgres psql -U postgres -c "
  CREATE TABLE IF NOT EXISTS _migrations (
    name TEXT PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );"

# Run migrations in order
APPLIED=0
FAILED=0
for migration in /opt/contentos/migrations/*.sql; do
  filename=$(basename "$migration")

  # Check if already applied
  SKIP=$(docker compose -f supabase/docker-compose.yml exec -T postgres psql -U postgres -t -c "
    SELECT EXISTS(SELECT 1 FROM _migrations WHERE name = '${filename}');" | tr -d ' ')

  if [ "$SKIP" = "t" ]; then
    echo "  SKIP  ${filename}"
    continue
  fi

  echo -n "  RUN   ${filename}..."
  if docker compose -f supabase/docker-compose.yml exec -T postgres psql -U postgres -f "/dev/stdin" < "$migration" > /dev/null 2>&1; then
    echo " OK"
    docker compose -f supabase/docker-compose.yml exec -T postgres psql -U postgres -c "
      INSERT INTO _migrations (name) VALUES ('${filename}') ON CONFLICT DO NOTHING;" > /dev/null 2>&1
    APPLIED=$((APPLIED + 1))
  else
    echo " FAILED"
    FAILED=$((FAILED + 1))
  fi
done

echo ""
echo "Applied: ${APPLIED} | Failed: ${FAILED}"
REMOTE_SCRIPT

# ── Step 6: Print connection details ──
echo ""
echo "=== Deployment Complete ==="
echo ""

ssh "${SERVER}" bash <<'REMOTE_SCRIPT'
source /opt/contentos/supabase/.env
SERVER_IP=$(hostname -I | awk '{print $1}')

echo "Connection details for your Vercel apps:"
echo ""
echo "  NEXT_PUBLIC_SUPABASE_URL=${API_EXTERNAL_URL}"
echo "  NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}"
echo "  SUPABASE_SERVICE_KEY=${SERVICE_ROLE_KEY}"
echo "  SUPABASE_DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@${SERVER_IP}:5432/postgres"
echo ""
echo "  Supabase Studio: http://${SERVER_IP}:3001"
echo "  Kong API Gateway: http://${SERVER_IP}:8000"
echo ""
echo "Save these values — you'll need them for Vercel environment variables."
REMOTE_SCRIPT
