#!/usr/bin/env bash
# ============================================================
# Generate JWT keys for self-hosted Supabase
# ============================================================
# Usage: ./generate-keys.sh [output-file]
# Default output: ../supabase/.env.keys
#
# Generates:
#   - JWT_SECRET (random 64-char hex)
#   - ANON_KEY (JWT with anon role)
#   - SERVICE_ROLE_KEY (JWT with service_role, bypasses RLS)
# ============================================================

set -euo pipefail

OUTPUT_FILE="${1:-$(dirname "$0")/../supabase/.env.keys}"

# Check for required tools
if ! command -v openssl &> /dev/null; then
  echo "Error: openssl is required but not found"
  exit 1
fi

# Generate JWT secret
JWT_SECRET=$(openssl rand -hex 32)
echo "Generated JWT_SECRET: ${JWT_SECRET:0:8}..."

# JWT header (alg: HS256, typ: JWT)
HEADER=$(echo -n '{"alg":"HS256","typ":"JWT"}' | openssl base64 -e | tr -d '=' | tr '/+' '_-' | tr -d '\n')

# Anon key payload (role: anon, iss: supabase)
ANON_PAYLOAD=$(echo -n "{\"role\":\"anon\",\"iss\":\"supabase\",\"iat\":$(date +%s),\"exp\":$(($(date +%s) + 315360000))}" | openssl base64 -e | tr -d '=' | tr '/+' '_-' | tr -d '\n')

# Service role key payload (role: service_role, iss: supabase)
SERVICE_PAYLOAD=$(echo -n "{\"role\":\"service_role\",\"iss\":\"supabase\",\"iat\":$(date +%s),\"exp\":$(($(date +%s) + 315360000))}" | openssl base64 -e | tr -d '=' | tr '/+' '_-' | tr -d '\n')

# Sign with HMAC-SHA256
ANON_SIGNATURE=$(echo -n "${HEADER}.${ANON_PAYLOAD}" | openssl dgst -binary -sha256 -hmac "${JWT_SECRET}" | openssl base64 -e | tr -d '=' | tr '/+' '_-' | tr -d '\n')
SERVICE_SIGNATURE=$(echo -n "${HEADER}.${SERVICE_PAYLOAD}" | openssl dgst -binary -sha256 -hmac "${JWT_SECRET}" | openssl base64 -e | tr -d '=' | tr '/+' '_-' | tr -d '\n')

ANON_KEY="${HEADER}.${ANON_PAYLOAD}.${ANON_SIGNATURE}"
SERVICE_ROLE_KEY="${HEADER}.${SERVICE_PAYLOAD}.${SERVICE_SIGNATURE}"

# Write to file
cat > "${OUTPUT_FILE}" << EOF
# Generated by generate-keys.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Copy these values into your .env file

JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
EOF

echo ""
echo "Keys written to: ${OUTPUT_FILE}"
echo ""
echo "Copy these into your infra/supabase/.env file:"
echo "  JWT_SECRET=${JWT_SECRET}"
echo "  ANON_KEY=${ANON_KEY:0:40}..."
echo "  SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY:0:40}..."
echo ""
echo "Also update your app .env files:"
echo "  SUPABASE_URL=http://localhost:8000"
echo "  SUPABASE_ANON_KEY=<ANON_KEY from above>"
echo "  SUPABASE_SERVICE_KEY=<SERVICE_ROLE_KEY from above>"
