// @crumb image-editor-templates
// DATA | image-editor | template-presets
// why: Pre-designed canvas templates for common social media formats
// in:[template-selection] out:[fabric-canvas-JSON] err:[invalid-template]

export interface TemplateObject {
  type: string;
  [key: string]: unknown;
}

export interface TemplatePreset {
  id: string;
  name: string;
  description: string;
  width: number;
  height: number;
  backgroundColor: string;
  objects: TemplateObject[];
}

export const TEMPLATE_PRESETS: TemplatePreset[] = [
  {
    id: 'social-post',
    name: 'Social Post',
    description: 'Gradient background with centered text',
    width: 1080,
    height: 1080,
    backgroundColor: '#4f46e5',
    objects: [
      {
        type: 'Rect',
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: {
          type: 'linear',
          coords: { x1: 0, y1: 0, x2: 1080, y2: 1080 },
          colorStops: [
            { offset: 0, color: '#4f46e5' },
            { offset: 1, color: '#7c3aed' },
          ],
        },
        selectable: false,
        evented: false,
      },
      {
        type: 'Textbox',
        left: 140,
        top: 400,
        width: 800,
        text: 'Your Message Here',
        fontSize: 72,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fill: '#ffffff',
        textAlign: 'center',
      },
      {
        type: 'Textbox',
        left: 240,
        top: 520,
        width: 600,
        text: 'Add your subtitle or caption',
        fontSize: 32,
        fontFamily: 'Arial',
        fill: 'rgba(255,255,255,0.8)',
        textAlign: 'center',
      },
    ],
  },
  {
    id: 'quote-card',
    name: 'Quote Card',
    description: 'Dark background with large quote text',
    width: 1080,
    height: 1080,
    backgroundColor: '#111827',
    objects: [
      {
        type: 'Rect',
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: '#111827',
        selectable: false,
        evented: false,
      },
      {
        type: 'Textbox',
        left: 120,
        top: 200,
        width: 840,
        text: '\u201cYour inspiring quote goes here. Make it count.\u201d',
        fontSize: 56,
        fontFamily: 'Georgia',
        fontStyle: 'italic',
        fill: '#f9fafb',
        textAlign: 'center',
        lineHeight: 1.4,
      },
      {
        type: 'Rect',
        left: 440,
        top: 620,
        width: 200,
        height: 2,
        fill: '#d4f85a',
        selectable: true,
      },
      {
        type: 'Textbox',
        left: 240,
        top: 660,
        width: 600,
        text: '— Author Name',
        fontSize: 28,
        fontFamily: 'Arial',
        fill: '#9ca3af',
        textAlign: 'center',
      },
    ],
  },
  {
    id: 'announcement',
    name: 'Announcement',
    description: 'Brand color with heading, subheading and CTA',
    width: 1080,
    height: 1080,
    backgroundColor: '#2563eb',
    objects: [
      {
        type: 'Rect',
        left: 0,
        top: 0,
        width: 1080,
        height: 1080,
        fill: '#2563eb',
        selectable: false,
        evented: false,
      },
      {
        type: 'Textbox',
        left: 100,
        top: 160,
        width: 880,
        text: 'BIG ANNOUNCEMENT',
        fontSize: 36,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fill: 'rgba(255,255,255,0.7)',
        textAlign: 'center',
        charSpacing: 300,
      },
      {
        type: 'Textbox',
        left: 80,
        top: 260,
        width: 920,
        text: 'Your Main Headline Here',
        fontSize: 80,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fill: '#ffffff',
        textAlign: 'center',
      },
      {
        type: 'Textbox',
        left: 160,
        top: 480,
        width: 760,
        text: 'Describe your announcement in a short, compelling subheading that drives action.',
        fontSize: 30,
        fontFamily: 'Arial',
        fill: 'rgba(255,255,255,0.85)',
        textAlign: 'center',
        lineHeight: 1.5,
      },
      {
        type: 'Rect',
        left: 340,
        top: 680,
        width: 400,
        height: 80,
        rx: 40,
        ry: 40,
        fill: '#ffffff',
        selectable: true,
      },
      {
        type: 'Textbox',
        left: 340,
        top: 697,
        width: 400,
        text: 'Learn More',
        fontSize: 28,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fill: '#2563eb',
        textAlign: 'center',
      },
    ],
  },
  {
    id: 'story-template',
    name: 'Story Template',
    description: '1080x1920 portrait with text overlay',
    width: 1080,
    height: 1920,
    backgroundColor: '#0f172a',
    objects: [
      {
        type: 'Rect',
        left: 0,
        top: 0,
        width: 1080,
        height: 1920,
        fill: '#0f172a',
        selectable: false,
        evented: false,
      },
      {
        type: 'Rect',
        left: 60,
        top: 120,
        width: 960,
        height: 1100,
        rx: 20,
        ry: 20,
        fill: '#1e293b',
        stroke: '#334155',
        strokeWidth: 2,
        selectable: true,
      },
      {
        type: 'Textbox',
        left: 100,
        top: 200,
        width: 880,
        text: 'Image Placeholder',
        fontSize: 28,
        fontFamily: 'Arial',
        fill: '#64748b',
        textAlign: 'center',
      },
      {
        type: 'Rect',
        left: 0,
        top: 1360,
        width: 1080,
        height: 560,
        fill: 'rgba(0,0,0,0.85)',
        selectable: false,
        evented: false,
      },
      {
        type: 'Textbox',
        left: 80,
        top: 1420,
        width: 920,
        text: 'Story Title',
        fontSize: 72,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fill: '#ffffff',
        textAlign: 'left',
      },
      {
        type: 'Textbox',
        left: 80,
        top: 1540,
        width: 920,
        text: 'Swipe up to learn more about this story and what makes it special.',
        fontSize: 32,
        fontFamily: 'Arial',
        fill: 'rgba(255,255,255,0.8)',
        textAlign: 'left',
        lineHeight: 1.4,
      },
    ],
  },
  {
    id: 'linkedin-banner',
    name: 'LinkedIn Banner',
    description: '1584x396 professional layout',
    width: 1584,
    height: 396,
    backgroundColor: '#1d4ed8',
    objects: [
      {
        type: 'Rect',
        left: 0,
        top: 0,
        width: 1584,
        height: 396,
        fill: {
          type: 'linear',
          coords: { x1: 0, y1: 0, x2: 1584, y2: 0 },
          colorStops: [
            { offset: 0, color: '#1d4ed8' },
            { offset: 1, color: '#0f172a' },
          ],
        },
        selectable: false,
        evented: false,
      },
      {
        type: 'Textbox',
        left: 80,
        top: 100,
        width: 900,
        text: 'Your Name or Company',
        fontSize: 64,
        fontFamily: 'Arial',
        fontWeight: 'bold',
        fill: '#ffffff',
        textAlign: 'left',
      },
      {
        type: 'Textbox',
        left: 80,
        top: 200,
        width: 800,
        text: 'Your Title | Specialization | Key Achievement',
        fontSize: 28,
        fontFamily: 'Arial',
        fill: 'rgba(255,255,255,0.75)',
        textAlign: 'left',
      },
      {
        type: 'Rect',
        left: 80,
        top: 270,
        width: 120,
        height: 4,
        fill: '#d4f85a',
        selectable: true,
      },
    ],
  },
];
