-- Realtime schema setup
BEGIN;
  CREATE SCHEMA IF NOT EXISTS _realtime;
  GRANT USAGE ON SCHEMA _realtime TO postgres;
  ALTER DEFAULT PRIVILEGES IN SCHEMA _realtime GRANT ALL ON TABLES TO postgres;
  ALTER DEFAULT PRIVILEGES IN SCHEMA _realtime GRANT ALL ON SEQUENCES TO postgres;
  ALTER DEFAULT PRIVILEGES IN SCHEMA _realtime GRANT ALL ON ROUTINES TO postgres;
COMMIT;
